---
- name: Basic tasks
  hosts: my-localhost
  gather_facts: yes
  vars:
    application_infra_tag: "{{ application_infra_tag }}"
    is_verify: "{{ is_verify }}"
  tasks:
    - name: Show deployment info
      debug:
        msg:  |
          Tag of the pipeline: {{ application_infra_tag }}
          Is Verify Pipeline: {{ is_verify }}

    - name: Check OS release
      command: cat /etc/os-release
      register: os_result
    - debug: var=os_result.stdout_lines
